### ISSUE TITLE
Player Taking Damage / Hitstun Frame

### ISSUE THREAD

**Issue by joshuaryoung** [joshuaryoung/gameWithAlex#12]

**Comment by haibu64** [comment]
![hitspark_3](https://user-images.githubusercontent.com/55934781/71531851-d2d74d00-28ad-11ea-9a04-980b046a5647.png)
![PlayerCharacterHit](https://user-images.githubusercontent.com/55934781/71531852-d2d74d00-28ad-11ea-8141-50e719485742.png)
![hitspark_1](https://user-images.githubusercontent.com/55934781/71531853-d2d74d00-28ad-11ea-96b1-36fc6e7193c7.png)
![hitspark_2](https://user-images.githubusercontent.com/55934781/71531854-d36fe380-28ad-11ea-8d86-d5cadbf1e9fa.png)
